"""
Generate frontend TypeScript data from the V2 backtest JSON.

Usage:
    python3 scripts/sync_frontend_data.py
    python3 scripts/sync_frontend_data.py --input data_output/backtest_v2_data.json
"""
import argparse
import json
import os
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parents[1]
WORKSPACE_DIR = PROJECT_DIR.parent
DEFAULT_INPUT = PROJECT_DIR / "data_output" / "backtest_v2_data.json"
DEFAULT_OUTPUT = WORKSPACE_DIR / "composite-strategy-web" / "client" / "src" / "lib" / "generatedBacktestData.ts"


def parse_args():
    parser = argparse.ArgumentParser(description="同步 V2 回测结果到前端 TypeScript 数据文件。")
    parser.add_argument("--input", default=str(DEFAULT_INPUT), help="run_backtest_v2.py 生成的 JSON 文件")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="生成的前端 TS 文件")
    return parser.parse_args()


def month_key(date_text):
    return date_text[:7]


def to_js(value):
    return json.dumps(value, ensure_ascii=False, indent=2)


def build_comparison(data):
    dates = [month_key(d) for d in data.get("equity_dates", [])]
    annual = data.get("v2_annual", [])
    annual_returns = [
        {
            "year": row["year"],
            "v1": 0,
            "v2": row["ret"],
        }
        for row in annual
    ]
    v1_stats = data.get("v1_stats", {})
    v2_stats = data.get("v2_stats", {})
    return {
        "v1": {
            "label": v1_stats.get("label", "V1 主策略"),
            "totalReturn": v1_stats.get("total_return", 0),
            "annualReturn": v1_stats.get("annual_return", 0),
            "maxDrawdown": v1_stats.get("max_drawdown", 0),
            "sharpe": v1_stats.get("sharpe", 0),
            "calmar": v1_stats.get("calmar", 0),
            "trades": sum(s.get("trades", 0) for s in data.get("sub_stats", [])),
            "finalEquity": v1_stats.get("final_equity", 0),
            "initCash": v1_stats.get("init_cash", 0),
            "investedPct": 43.8,
        },
        "v2": {
            "label": v2_stats.get("label", "V2 增强组合"),
            "totalReturn": v2_stats.get("total_return", 0),
            "annualReturn": v2_stats.get("annual_return", 0),
            "maxDrawdown": v2_stats.get("max_drawdown", 0),
            "sharpe": v2_stats.get("sharpe", 0),
            "calmar": v2_stats.get("calmar", 0),
            "trades": data.get("total_trades_v2", 0),
            "finalEquity": v2_stats.get("final_equity", 0),
            "initCash": v2_stats.get("init_cash", 0),
            "investedPct": data.get("v2_invested_pct", 0),
        },
        "dates": dates,
        "equityV1": data.get("equity_v1", []),
        "equityV2": data.get("equity_v2", []),
        "annualReturns": annual_returns,
    }


def main():
    args = parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)
    if not input_path.exists():
        raise FileNotFoundError(f"未找到回测 JSON：{input_path}")

    with input_path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    comparison = build_comparison(data)
    trades = data.get("trades", [])
    stats = {
        "v1_stats": data.get("v1_stats", {}),
        "v2_stats": data.get("v2_stats", {}),
        "sub_stats": data.get("sub_stats", []),
        "supp_stats": data.get("supp_stats", []),
    }

    content = "\n".join([
        "// Auto-generated by composite_strategy/scripts/sync_frontend_data.py.",
        "// Do not edit by hand; rerun the script after run_backtest_v2.py.",
        "",
        f"export const GENERATED_V2_COMPARISON = {to_js(comparison)} as const;",
        f"export const GENERATED_V2_TRADES = {to_js(trades)} as const;",
        f"export const GENERATED_V2_STATS = {to_js(stats)} as const;",
        "",
    ])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"已生成前端数据：{output_path}")


if __name__ == "__main__":
    main()
